spring.application.name=pw

# Configurazione flessibile per la sorgente dati
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/forum_pugliamare?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# Driver e Dialetto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Ottimizzazione Timeout Hikari per l'avvio in Docker
spring.datasource.hikari.connection-timeout=45000
spring.datasource.hikari.initialization-fail-timeout=60000

# Durata della sessione utente prima di richiedere di nuovo il login
server.servlet.session.timeout=2d
